# Generated by Django 4.2.5 on 2023-10-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_model',
            name='p_id',
        ),
    ]
