# Generated by Django 4.2.5 on 2023-10-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_product_model_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='p_desc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
