# Generated by Django 4.2.5 on 2023-10-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_cart_item_total_alter_cart_item_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_model',
            name='items',
        ),
        migrations.AddField(
            model_name='cart_model',
            name='product',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cart_model',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
