# Generated by Django 4.2.5 on 2023-10-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_cart_model_items_cart_model_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_model',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart_model',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart_model',
            name='items',
            field=models.ManyToManyField(to='mainapp.cart_item'),
        ),
    ]
