# Generated by Django 4.2.5 on 2023-10-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_cart_model_product_remove_cart_model_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='total',
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
